language: cpp
dist: xenial
compiler:
  - g++

install:
  # install conan
  - pip install conan
  # config conan for current system
  - conan user
script:
  - mkdir build && cd build
  - conan install .. --build
  - cmake ..
  - cmake --build .
  - ./bin/mathlib_tests
